#!/bin/bash

#Merge samples sequenced on multiple lanes

for file in `ls | sort | cut -d'_' -f 1 | uniq`; do
  cat ${file}*_R1* > ../fastq_merged/${file}_R1_001.fastq.gz
  cat ${file}*_R2* > ../fastq_merged/${file}_R2_001.fastq.gz
done
